### ISSUE TITLE
Typeahead 0.10.2 Breaks FastClick

### ISSUE THREAD

**Issue by mutewinter** [twitter/typeahead.js#792]
I'm using typeahead.bundle.js via Bower. I had been using 0.10.1 happily for a few weeks along-side [FastClick](https://github.com/ftlabs/fastclick). However, upon upgrading to 0.10.2, FastClick no longer allows suggestions to be tapped on iOS.

I compared diffs between 0.10.1 and 0.10.2, but could not find the cuprit. Adding `class="needsclick"` in the template for the suggestion allows the non-bold region of the suggestion to be tapped. For now, I'm locking my version at 0.10.1 until there is workaround / resolution.

**Comment by jharding** [comment]
fastclick compatibility should be fixed in v0.11.

**Comment by designbyadrian** [comment]
Having problems with 0.11.1 and FastClick 1.0.6.

**Comment by andycorm** [comment]
Also having problems with Typeahead version 0.11.1 and FastClick 1.0.6. (Even with adding the necessary 'needsclick' class.)

**Comment by lloydmeta** [comment]
Same, having issues w/ 0.11.1 and FastClick 1.0.6

**Comment by prabasak** [comment]
Is anything done for the latest version 0.11.1. This non-support for touch devices still persists.
